/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class InstructionsJFrame extends javax.swing.JFrame {

    /**
     * Creates new form InstructionsJFrame
     */
    public InstructionsJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        lblWelcomeTitlePic = new javax.swing.JLabel();
        lblInstruction1 = new javax.swing.JLabel();
        lblInstruction2 = new javax.swing.JLabel();
        lblInstruction3 = new javax.swing.JLabel();
        lblInstruction4 = new javax.swing.JLabel();
        lblInstruction5 = new javax.swing.JLabel();
        lblInstruction6 = new javax.swing.JLabel();
        lblInstruction7 = new javax.swing.JLabel();
        lblInstruction8 = new javax.swing.JLabel();
        lblInstruction9 = new javax.swing.JLabel();
        lblInstruction10 = new javax.swing.JLabel();
        lblInstruction11 = new javax.swing.JLabel();
        lblInstruction12 = new javax.swing.JLabel();
        lblInstruction13 = new javax.swing.JLabel();
        lblInstruction14 = new javax.swing.JLabel();
        lblInstruction15 = new javax.swing.JLabel();
        lblInstruction16 = new javax.swing.JLabel();
        lblInstruction17 = new javax.swing.JLabel();
        btnLastLevelSpoiler = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1088, 744));
        setResizable(false);
        getContentPane().setLayout(null);

        pnlBack.setBackground(new java.awt.Color(51, 51, 51));
        pnlBack.setMaximumSize(new java.awt.Dimension(1088, 744));
        pnlBack.setMinimumSize(new java.awt.Dimension(1088, 744));
        pnlBack.setPreferredSize(new java.awt.Dimension(1088, 744));

        lblWelcomeTitlePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InstructionsPrompt.png"))); // NOI18N
        lblWelcomeTitlePic.setMaximumSize(new java.awt.Dimension(125, 989));
        lblWelcomeTitlePic.setMinimumSize(new java.awt.Dimension(125, 989));
        lblWelcomeTitlePic.setPreferredSize(new java.awt.Dimension(125, 989));

        lblInstruction1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInstruction1.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction1.setText("Objective:");

        lblInstruction2.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction2.setText("Beat the bosses in each level and progress far enough to battle the final boss!");

        lblInstruction3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInstruction3.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction3.setText("How to Play:");

        lblInstruction4.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction4.setText("Click the \"Roll The Dice\" button in order to damage the boss you are facing. Everytime you roll the dice, the boss will too!");

        lblInstruction5.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction5.setText("HINT: You can press the skip move button to see what the boss usually rolls or predict their next roll!");

        lblInstruction7.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction7.setText("If your HP goes to zero or below, you lose and you can restart the game. If the boss' HP goes to 0 or below you win!");

        lblInstruction8.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction8.setText("Then you will see your upgrade options! Depending on the level you can choose from Luck, Health, Damage, Saving Throw, and BFG.");

        lblInstruction9.setForeground(new java.awt.Color(102, 255, 102));
        lblInstruction9.setText("Luck: Gain 30 HP and increase your chances of rolling a higher number!");

        lblInstruction10.setForeground(new java.awt.Color(102, 102, 255));
        lblInstruction10.setText("Health: Gain 100 HP! ");

        lblInstruction11.setForeground(new java.awt.Color(255, 0, 51));
        lblInstruction11.setText("Damage: Gain 20 HP and add 1 to your Damage Multiplier (located at the banner on top of the screen). ");

        lblInstruction12.setForeground(new java.awt.Color(255, 255, 102));
        lblInstruction12.setText("Saving Throw: Randomly gain 1 - 200 HP! ");

        lblInstruction13.setForeground(java.awt.Color.orange);
        lblInstruction13.setText("BFG: Cut all boss' HP in half!");

        lblInstruction14.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction14.setText("The top banner keeps track of your Damage Multiplier, Luck, and Max Health. You can also find the exit and restart buttons there. ");

        lblInstruction15.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction15.setText("Additionally, you will see the Devil Contract option. If you dare to make a deal with the Devil, you have the chance to gain or lose 50 HP. (You can roll it 2 times by default)");

        lblInstruction16.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction16.setText("If you are lucky enough and you trick the Devil, you will gain 100 HP and 1 damage multiplier + you will be able to roll it again right away! ");

        lblInstruction17.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction17.setText("After defeating all 7 bosses, you will face the final boss.");

        btnLastLevelSpoiler.setBackground(new java.awt.Color(0, 0, 0));
        btnLastLevelSpoiler.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnLastLevelSpoiler.setForeground(new java.awt.Color(255, 0, 0));
        btnLastLevelSpoiler.setText("LAST LEVEL SPOILER ----->");
        btnLastLevelSpoiler.setMaximumSize(new java.awt.Dimension(199, 37));
        btnLastLevelSpoiler.setMinimumSize(new java.awt.Dimension(199, 37));
        btnLastLevelSpoiler.setPreferredSize(new java.awt.Dimension(199, 37));
        btnLastLevelSpoiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastLevelSpoilerActionPerformed(evt);
            }
        });

        btnGoBack.setBackground(new java.awt.Color(0, 0, 0));
        btnGoBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGoBack.setForeground(new java.awt.Color(255, 0, 0));
        btnGoBack.setText("<----- Go Back");
        btnGoBack.setMaximumSize(new java.awt.Dimension(199, 37));
        btnGoBack.setMinimumSize(new java.awt.Dimension(199, 37));
        btnGoBack.setPreferredSize(new java.awt.Dimension(199, 37));
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackLayout = new javax.swing.GroupLayout(pnlBack);
        pnlBack.setLayout(pnlBackLayout);
        pnlBackLayout.setHorizontalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackLayout.createSequentialGroup()
                .addGroup(pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBackLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInstruction1)
                            .addComponent(lblInstruction2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInstruction3)
                            .addComponent(lblInstruction5)
                            .addComponent(lblInstruction4)
                            .addComponent(lblInstruction6)
                            .addComponent(lblInstruction7)
                            .addComponent(lblInstruction8)
                            .addComponent(lblInstruction9)
                            .addComponent(lblInstruction10)
                            .addComponent(lblInstruction11)
                            .addComponent(lblInstruction12)
                            .addComponent(lblInstruction13)
                            .addComponent(lblInstruction14)
                            .addComponent(lblInstruction16)
                            .addComponent(lblInstruction17)
                            .addComponent(lblInstruction15)
                            .addGroup(pnlBackLayout.createSequentialGroup()
                                .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLastLevelSpoiler, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlBackLayout.createSequentialGroup()
                        .addContainerGap(38, Short.MAX_VALUE)
                        .addComponent(lblWelcomeTitlePic, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        pnlBackLayout.setVerticalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblWelcomeTitlePic, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruction1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruction2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInstruction6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruction3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruction4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruction5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruction7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruction8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruction9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruction10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruction11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruction12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruction13)
                .addGap(18, 18, 18)
                .addComponent(lblInstruction14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruction15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruction16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruction17)
                .addGap(18, 18, 18)
                .addGroup(pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLastLevelSpoiler, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBack);
        pnlBack.setBounds(0, 0, 1088, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLastLevelSpoilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastLevelSpoilerActionPerformed
        LastLevelInstructions frame4 = new LastLevelInstructions();
        this.setVisible(false);
        frame4.setVisible(true);
    }//GEN-LAST:event_btnLastLevelSpoilerActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        StartingJFrame1 frame3 = new StartingJFrame1();
        this.setVisible(false);
        frame3.setVisible(true);
    }//GEN-LAST:event_btnGoBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructionsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructionsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructionsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructionsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructionsJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnLastLevelSpoiler;
    private javax.swing.JLabel lblInstruction1;
    private javax.swing.JLabel lblInstruction10;
    private javax.swing.JLabel lblInstruction11;
    private javax.swing.JLabel lblInstruction12;
    private javax.swing.JLabel lblInstruction13;
    private javax.swing.JLabel lblInstruction14;
    private javax.swing.JLabel lblInstruction15;
    private javax.swing.JLabel lblInstruction16;
    private javax.swing.JLabel lblInstruction17;
    private javax.swing.JLabel lblInstruction2;
    private javax.swing.JLabel lblInstruction3;
    private javax.swing.JLabel lblInstruction4;
    private javax.swing.JLabel lblInstruction5;
    private javax.swing.JLabel lblInstruction6;
    private javax.swing.JLabel lblInstruction7;
    private javax.swing.JLabel lblInstruction8;
    private javax.swing.JLabel lblInstruction9;
    private javax.swing.JLabel lblWelcomeTitlePic;
    private javax.swing.JPanel pnlBack;
    // End of variables declaration//GEN-END:variables
}
