/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class LastLevelInstructions extends javax.swing.JFrame {

    /**
     * Creates new form LastLevelInstructions
     */
    public LastLevelInstructions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        lblTitlePic = new javax.swing.JLabel();
        btnGoBackLastLevel = new javax.swing.JButton();
        lblInstruction1 = new javax.swing.JLabel();
        lblInstruction2 = new javax.swing.JLabel();
        lblInstruction3 = new javax.swing.JLabel();
        lblInstruction4 = new javax.swing.JLabel();
        lblInstruction5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1088, 744));
        setResizable(false);
        getContentPane().setLayout(null);

        pnlBack.setBackground(new java.awt.Color(51, 51, 51));
        pnlBack.setMaximumSize(new java.awt.Dimension(1088, 744));
        pnlBack.setMinimumSize(new java.awt.Dimension(1088, 744));
        pnlBack.setPreferredSize(new java.awt.Dimension(1088, 744));

        lblTitlePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LastLevelInstructions.png"))); // NOI18N

        btnGoBackLastLevel.setBackground(new java.awt.Color(0, 0, 0));
        btnGoBackLastLevel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGoBackLastLevel.setForeground(new java.awt.Color(255, 0, 0));
        btnGoBackLastLevel.setText(" <----- Go  Back");
        btnGoBackLastLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackLastLevelActionPerformed(evt);
            }
        });

        lblInstruction1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInstruction1.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction1.setText("For those of you who are brave enough to face the final boss, you will need to find and hit 3 of the boss' weakpoints.");

        lblInstruction2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInstruction2.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction2.setText("You will \"hit\" the boss by clicking the buttons that show up on your screen. Only four buttons will appear at a time.");

        lblInstruction3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInstruction3.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction3.setText("One weakpoint will be good, one will be moderate, and the last will be a trick! So, be careful. ");

        lblInstruction4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInstruction4.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction4.setText("You may also choose to attack the boss without hitting the weakpoints. ");

        lblInstruction5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInstruction5.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction5.setText("By doing so you will heal with 25 HP and damage the boss by 25 HP.");

        javax.swing.GroupLayout pnlBackLayout = new javax.swing.GroupLayout(pnlBack);
        pnlBack.setLayout(pnlBackLayout);
        pnlBackLayout.setHorizontalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGoBackLastLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addGroup(pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInstruction4)
                            .addComponent(lblInstruction1)
                            .addComponent(lblInstruction2)
                            .addComponent(lblInstruction3)
                            .addComponent(lblInstruction5)))
                    .addGroup(pnlBackLayout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(lblTitlePic)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackLayout.setVerticalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lblTitlePic)
                .addGap(57, 57, 57)
                .addComponent(lblInstruction1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInstruction2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInstruction3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInstruction4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInstruction5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(btnGoBackLastLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        getContentPane().add(pnlBack);
        pnlBack.setBounds(0, 0, 1090, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoBackLastLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackLastLevelActionPerformed
        InstructionsJFrame frame5 = new InstructionsJFrame();
        this.setVisible(false);
        frame5.setVisible(true);
    }//GEN-LAST:event_btnGoBackLastLevelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LastLevelInstructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LastLevelInstructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LastLevelInstructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LastLevelInstructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LastLevelInstructions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBackLastLevel;
    private javax.swing.JLabel lblInstruction1;
    private javax.swing.JLabel lblInstruction2;
    private javax.swing.JLabel lblInstruction3;
    private javax.swing.JLabel lblInstruction4;
    private javax.swing.JLabel lblInstruction5;
    private javax.swing.JLabel lblTitlePic;
    private javax.swing.JPanel pnlBack;
    // End of variables declaration//GEN-END:variables
}
