
import static java.lang.Thread.sleep;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Goldnova115
 */
public class StartingJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form StartingJFrame1
     */
  
    public StartingJFrame1() {
        initComponents();
         //btnLuck1.setEnabled(false);
           //btnLuck1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart = new javax.swing.JButton();
        btnInstructions = new javax.swing.JButton();
        lblTitlePic = new javax.swing.JLabel();
        btnBackPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1088, 744));
        getContentPane().setLayout(null);

        btnStart.setBackground(new java.awt.Color(0, 0, 0));
        btnStart.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 0, 0));
        btnStart.setText("Press to start!");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart);
        btnStart.setBounds(70, 490, 458, 110);

        btnInstructions.setBackground(new java.awt.Color(0, 0, 0));
        btnInstructions.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnInstructions.setForeground(new java.awt.Color(255, 0, 0));
        btnInstructions.setText("Instructions");
        btnInstructions.setMaximumSize(new java.awt.Dimension(101, 23));
        btnInstructions.setMinimumSize(new java.awt.Dimension(101, 23));
        btnInstructions.setPreferredSize(new java.awt.Dimension(101, 23));
        btnInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructionsActionPerformed(evt);
            }
        });
        getContentPane().add(btnInstructions);
        btnInstructions.setBounds(550, 490, 458, 107);

        lblTitlePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BossSlayerTitle.png"))); // NOI18N
        lblTitlePic.setText("jLabel1");
        lblTitlePic.setMaximumSize(new java.awt.Dimension(484, 120));
        lblTitlePic.setMinimumSize(new java.awt.Dimension(484, 120));
        lblTitlePic.setPreferredSize(new java.awt.Dimension(484, 120));
        getContentPane().add(lblTitlePic);
        lblTitlePic.setBounds(310, 190, 484, 120);

        btnBackPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StartingBackground.jpg"))); // NOI18N
        btnBackPic.setMaximumSize(new java.awt.Dimension(1088, 744));
        btnBackPic.setMinimumSize(new java.awt.Dimension(1088, 744));
        btnBackPic.setPreferredSize(new java.awt.Dimension(1088, 744));
        getContentPane().add(btnBackPic);
        btnBackPic.setBounds(0, 0, 1088, 744);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
  
        JFrame_v1 frame2 = new JFrame_v1();
    this.setVisible(false);
    frame2.setVisible(true);
    
    
    // You can also use  MyFrame1.this.dispose(); dependind if you ever need to use that frame again
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstructionsActionPerformed
     InstructionsJFrame frame2 = new InstructionsJFrame();
        this.setVisible(false);
        frame2.setVisible(true);
    }//GEN-LAST:event_btnInstructionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartingJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartingJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartingJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartingJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartingJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBackPic;
    private javax.swing.JButton btnInstructions;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblTitlePic;
    // End of variables declaration//GEN-END:variables
}
